[build]
  publish = "."
  functions = "netlify/functions" # Explicitly define the functions directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  FIREBASE_API_KEY = "AIzaSyDuKns6v5EOUDL-aZXMA2i6223aquQzo1E"
  FIREBASE_AUTH_DOMAIN = "voter-card-scanner.firebaseapp.com"
  FIREBASE_PROJECT_ID = "voter-card-scanner"
  FIREBASE_STORAGE_BUCKET = "voter-card-scanner.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID = "665299220821"
  FIREBASE_APP_ID = "1:665299220821:web:f8025478a24f5375c697dc"
  FIREBASE_MEASUREMENT_ID = "G-G88F77H8VR" 